name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'v16.13.0'

      - run: npm install
      - run: npm run docs:build
      #- run: npm run test

      - uses: actions/upload-artifact@v2
        with:
          path: ./docs/.vitepress/dist

  deploy:
    needs: build

    runs-on: ubuntu-latest

    if: github.ref=='refs/heads/main'

    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./docs/.vitepress/dist

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist/artifact

      - name: aliyun-oss-website-action
        uses: fangbinwei/aliyun-oss-website-action@v1.3.0
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: enjoy-plus
          endpoint: oss-cn-beijing.aliyuncs.com
          folder: ./docs/.vitepress/dist/artifact
